### ISSUE TITLE
kdab

### ISSUE THREAD

**Issue by Zianwar** [alaouy/ndpze63aexw29#1]

**Comment by kronik3r** [comment]
@Zianwar dkhalt ndir issue ntala3ha 3lih wana nl9ak sba9tini ;)

**Comment by Zianwar** [comment]
@kronik3r hahahah wa hanta katchouf nass katmout bach dir dik l3iba ou howa machi kay generiha
kdab lakhor hmar :smile:

**Comment by alaouy** [comment]
Kheliwna n3icho a ryoss legrona, This is not related to the language used in this repo, but you both should be hit in the face with a 3D printed chair made out of a 3D printed 3D printer ! bizo

**Comment by Zianwar** [comment]
wakha a sidi makayn bass
